version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    volumes:
      - .:/app
      - bundle:/bundle

volumes:
  dbdata:
  bundle:

